// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv9m68JnRxjjbR_XVE7-Z9GQiBpkf82D0',
    appId: '1:1009082169764:web:a40623603387fa8c80a931',
    messagingSenderId: '1009082169764',
    projectId: 'the-loop-d46af',
    authDomain: 'the-loop-d46af.firebaseapp.com',
    storageBucket: 'the-loop-d46af.firebasestorage.app',
    measurementId: 'G-FCHVLH84Z5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoj7rbHP5fxe9zu1QfGpzyzVlIfpAqHJE',
    appId: '1:1009082169764:android:eb87a67b2ffb147c80a931',
    messagingSenderId: '1009082169764',
    projectId: 'the-loop-d46af',
    storageBucket: 'the-loop-d46af.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTR2Y0PG-UajR-Uxdm-Sc0eFadIGiwxFw',
    appId: '1:1009082169764:ios:9798f3ead0bcbfa680a931',
    messagingSenderId: '1009082169764',
    projectId: 'the-loop-d46af',
    storageBucket: 'the-loop-d46af.firebasestorage.app',
    iosClientId: '1009082169764-v7fp2e06lk8j9vobkdeqci8m0aq4j4jk.apps.googleusercontent.com',
    iosBundleId: 'com.lopp.app',
  );
}
